# Test your FastAPI endpoints. Run with: uvicorn app.main:app --reload

GET http://127.0.0.1:8000/healthz
Accept: application/json

###

GET http://127.0.0.1:8000/readyz
Accept: application/json

###

GET http://127.0.0.1:8000/handover
Accept: application/json
Authorization: Bearer {{token}}

###
