"""create handover jobs

Revision ID: 51c5b2a2c5d2
Revises: 0001_handover
"""
from alembic import op
import sqlalchemy as sa

revision = '51c5b2a2c5d2'
down_revision = '0001_handover'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(idempotency_key) > 0', name=op.f('ck_idempotency_records_nonempty_key')),
    sa.CheckConstraint('length(request_fingerprint) = 64', name=op.f('ck_idempotency_records_sha256_fingerprint_length')),
    sa.ForeignKeyConstraint(['tenant_id', 'job_id'], ['handover_jobs.tenant_id', 'handover_jobs.id'], name='fk_idempotency_tenant_job', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tenant_id', 'actor_id', 'idempotency_key', name=op.f('pk_idempotency_records'))
    )
    op.create_index('ix_idempotency_tenant_job', 'idempotency_records', ['tenant_id', 'job_id'], unique=False)
    op.drop_index(op.f('uq_handover_original'), table_name='handover_draft_versions', postgresql_where="(version_kind = 'ai_original'::text)")
    op.drop_table('handover_draft_versions')
    op.drop_index(op.f('ix_evidence_manifests_job'), table_name='evidence_manifests')
    op.drop_table('evidence_manifests')
    op.add_column('dispatch_outbox', sa.Column('event_type', sa.String(length=100), server_default=sa.text("'handover.generate.requested'"), nullable=False))
    op.add_column('dispatch_outbox', sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.alter_column('dispatch_outbox', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_constraint(op.f('dispatch_outbox_tenant_id_job_id_dispatch_number_key'), 'dispatch_outbox', type_='unique')
    op.drop_index(op.f('ix_dispatch_outbox_due'), table_name='dispatch_outbox')
    op.create_index('ix_outbox_state_available', 'dispatch_outbox', ['state', 'available_at'], unique=False)
    op.create_unique_constraint('uq_outbox_job_event', 'dispatch_outbox', ['tenant_id', 'job_id', 'event_type'])
    op.drop_constraint(op.f('dispatch_outbox_tenant_id_job_id_fkey'), 'dispatch_outbox', type_='foreignkey')
    op.create_foreign_key('fk_outbox_tenant_job', 'dispatch_outbox', 'handover_jobs', ['tenant_id', 'job_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    op.drop_column('dispatch_outbox', 'attempts')
    op.drop_column('dispatch_outbox', 'lease_token')
    op.drop_column('dispatch_outbox', 'lease_expires_at')
    op.drop_column('dispatch_outbox', 'dispatch_number')
    op.drop_column('dispatch_outbox', 'failure_code')
    op.drop_column('dispatch_outbox', 'task_name')
    op.add_column('handover_jobs', sa.Column('trigger', sa.String(length=16), server_default=sa.text("'manual'"), nullable=False))
    op.add_column('handover_jobs', sa.Column('generation_revision', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('handover_jobs', sa.Column('result_id', sa.Uuid(), nullable=True))
    op.add_column('handover_jobs', sa.Column('error_code', sa.String(length=64), nullable=True))
    op.alter_column('handover_jobs', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=24),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::text"))
    op.drop_constraint(op.f('handover_jobs_tenant_id_id_key'), 'handover_jobs', type_='unique')
    op.drop_constraint(op.f('handover_jobs_tenant_id_idempotency_key_key'), 'handover_jobs', type_='unique')
    op.drop_constraint(op.f('handover_jobs_tenant_id_resident_id_id_key'), 'handover_jobs', type_='unique')
    op.drop_constraint(op.f('handover_jobs_tenant_id_resident_id_shift_start_shift_end_g_key'), 'handover_jobs', type_='unique')
    op.drop_constraint(op.f('handover_jobs_tenant_id_resident_id_shift_start_shift_end_i_key'), 'handover_jobs', type_='unique')
    op.drop_index(op.f('ix_handover_jobs_dispatch'), table_name='handover_jobs')
    op.drop_index(op.f('ix_handover_jobs_lease'), table_name='handover_jobs', postgresql_where="(state = 'running'::text)")
    op.drop_index(op.f('ix_handover_jobs_resident'), table_name='handover_jobs')
    op.create_index('ix_handover_jobs_tenant_resident_created', 'handover_jobs', ['tenant_id', 'resident_id', 'created_at'], unique=False)
    op.create_unique_constraint('uq_handover_job_generation', 'handover_jobs', ['tenant_id', 'resident_id', 'shift_start', 'shift_end', 'generation_revision'])
    op.create_unique_constraint('uq_handover_job_tenant_id', 'handover_jobs', ['tenant_id', 'id'])
    op.drop_constraint(op.f('handover_jobs_tenant_id_resident_id_shift_start_shift_end__fkey'), 'handover_jobs', type_='foreignkey')
    op.drop_column('handover_jobs', 'trigger_type')
    op.drop_column('handover_jobs', 'generation_number')
    op.drop_column('handover_jobs', 'attempts')
    op.drop_column('handover_jobs', 'timezone')
    op.drop_column('handover_jobs', 'lease_token')
    op.drop_column('handover_jobs', 'lease_expires_at')
    op.drop_column('handover_jobs', 'idempotency_key')
    op.drop_column('handover_jobs', 'purpose')
    op.drop_column('handover_jobs', 'failure_code')
    op.drop_column('handover_jobs', 'completed_at')
    op.drop_column('handover_jobs', 'started_at')
    op.drop_column('handover_jobs', 'max_attempts')
    op.drop_column('handover_jobs', 'service_identity')
    op.drop_column('handover_jobs', 'heartbeat_at')
    op.drop_column('handover_jobs', 'previous_job_id')
    op.drop_column('handover_jobs', 'next_attempt_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handover_jobs', sa.Column('next_attempt_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('handover_jobs', sa.Column('previous_job_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('handover_jobs', sa.Column('heartbeat_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('handover_jobs', sa.Column('service_identity', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('handover_jobs', sa.Column('max_attempts', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.add_column('handover_jobs', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('handover_jobs', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('handover_jobs', sa.Column('failure_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('handover_jobs', sa.Column('purpose', sa.TEXT(), server_default=sa.text("'handover_generation'::text"), autoincrement=False, nullable=False))
    op.add_column('handover_jobs', sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('handover_jobs', sa.Column('lease_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('handover_jobs', sa.Column('lease_token', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('handover_jobs', sa.Column('timezone', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('handover_jobs', sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('handover_jobs', sa.Column('generation_number', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('handover_jobs', sa.Column('trigger_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('handover_jobs_tenant_id_resident_id_shift_start_shift_end__fkey'), 'handover_jobs', 'handover_jobs', ['tenant_id', 'resident_id', 'shift_start', 'shift_end', 'previous_job_id'], ['tenant_id', 'resident_id', 'shift_start', 'shift_end', 'id'])
    op.drop_constraint('uq_handover_job_tenant_id', 'handover_jobs', type_='unique')
    op.drop_constraint('uq_handover_job_generation', 'handover_jobs', type_='unique')
    op.drop_index('ix_handover_jobs_tenant_resident_created', table_name='handover_jobs')
    op.create_index(op.f('ix_handover_jobs_resident'), 'handover_jobs', ['tenant_id', 'resident_id', sa.literal_column('shift_end DESC')], unique=False)
    op.create_index(op.f('ix_handover_jobs_lease'), 'handover_jobs', ['tenant_id', 'lease_expires_at'], unique=False, postgresql_where="(state = 'running'::text)")
    op.create_index(op.f('ix_handover_jobs_dispatch'), 'handover_jobs', ['tenant_id', 'state', 'next_attempt_at'], unique=False)
    op.create_unique_constraint(op.f('handover_jobs_tenant_id_resident_id_shift_start_shift_end_i_key'), 'handover_jobs', ['tenant_id', 'resident_id', 'shift_start', 'shift_end', 'id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('handover_jobs_tenant_id_resident_id_shift_start_shift_end_g_key'), 'handover_jobs', ['tenant_id', 'resident_id', 'shift_start', 'shift_end', 'generation_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('handover_jobs_tenant_id_resident_id_id_key'), 'handover_jobs', ['tenant_id', 'resident_id', 'id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('handover_jobs_tenant_id_idempotency_key_key'), 'handover_jobs', ['tenant_id', 'idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('handover_jobs_tenant_id_id_key'), 'handover_jobs', ['tenant_id', 'id'], postgresql_nulls_not_distinct=False)
    op.alter_column('handover_jobs', 'state',
               existing_type=sa.String(length=24),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::text"))
    op.drop_column('handover_jobs', 'error_code')
    op.drop_column('handover_jobs', 'result_id')
    op.drop_column('handover_jobs', 'generation_revision')
    op.drop_column('handover_jobs', 'trigger')
    op.add_column('dispatch_outbox', sa.Column('task_name', sa.TEXT(), server_default=sa.text("'intelligence.handover.generate'::text"), autoincrement=False, nullable=False))
    op.add_column('dispatch_outbox', sa.Column('failure_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('dispatch_outbox', sa.Column('dispatch_number', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('dispatch_outbox', sa.Column('lease_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('dispatch_outbox', sa.Column('lease_token', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('dispatch_outbox', sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint('fk_outbox_tenant_job', 'dispatch_outbox', type_='foreignkey')
    op.create_foreign_key(op.f('dispatch_outbox_tenant_id_job_id_fkey'), 'dispatch_outbox', 'handover_jobs', ['tenant_id', 'job_id'], ['tenant_id', 'id'])
    op.drop_constraint('uq_outbox_job_event', 'dispatch_outbox', type_='unique')
    op.drop_index('ix_outbox_state_available', table_name='dispatch_outbox')
    op.create_index(op.f('ix_dispatch_outbox_due'), 'dispatch_outbox', ['tenant_id', 'state', 'available_at'], unique=False)
    op.create_unique_constraint(op.f('dispatch_outbox_tenant_id_job_id_dispatch_number_key'), 'dispatch_outbox', ['tenant_id', 'job_id', 'dispatch_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('dispatch_outbox', 'state',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_column('dispatch_outbox', 'attempt_count')
    op.drop_column('dispatch_outbox', 'event_type')
    op.create_table('evidence_manifests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resident_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attempt_token', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('evidence_cutoff', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('coverage_complete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('source_checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("jsonb_typeof(sources) = 'array'::text", name=op.f('evidence_manifests_sources_check')),
    sa.CheckConstraint("jsonb_typeof(warnings) = 'array'::text", name=op.f('evidence_manifests_warnings_check')),
    sa.ForeignKeyConstraint(['tenant_id', 'resident_id', 'job_id'], ['handover_jobs.tenant_id', 'handover_jobs.resident_id', 'handover_jobs.id'], name=op.f('evidence_manifests_tenant_id_resident_id_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('evidence_manifests_pkey')),
    sa.UniqueConstraint('tenant_id', 'id', name=op.f('evidence_manifests_tenant_id_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('tenant_id', 'job_id', 'attempt_token', name=op.f('evidence_manifests_tenant_id_job_id_attempt_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('tenant_id', 'resident_id', 'job_id', 'id', name=op.f('evidence_manifests_tenant_id_resident_id_job_id_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_evidence_manifests_job'), 'evidence_manifests', ['tenant_id', 'job_id'], unique=False)
    op.create_table('handover_draft_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resident_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('manifest_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_kind', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('previous_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('authored_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('agent_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gateway_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("jsonb_typeof(sections) = 'array'::text", name=op.f('handover_draft_versions_sections_check')),
    sa.CheckConstraint("jsonb_typeof(warnings) = 'array'::text", name=op.f('handover_draft_versions_warnings_check')),
    sa.CheckConstraint("version_kind = 'ai_original'::text AND version_number = 1 AND previous_version_id IS NULL OR version_kind = 'staff_revision'::text AND version_number > 1 AND previous_version_id IS NOT NULL AND authored_by IS NOT NULL", name=op.f('handover_draft_versions_check')),
    sa.CheckConstraint("version_kind = ANY (ARRAY['ai_original'::text, 'staff_revision'::text])", name=op.f('handover_draft_versions_version_kind_check')),
    sa.CheckConstraint('previous_version_id IS NULL OR previous_version_id <> id', name=op.f('handover_draft_versions_check1')),
    sa.CheckConstraint('version_number > 0', name=op.f('handover_draft_versions_version_number_check')),
    sa.ForeignKeyConstraint(['tenant_id', 'job_id', 'previous_version_id'], ['handover_draft_versions.tenant_id', 'handover_draft_versions.job_id', 'handover_draft_versions.id'], name=op.f('handover_draft_versions_tenant_id_job_id_previous_version__fkey')),
    sa.ForeignKeyConstraint(['tenant_id', 'resident_id', 'job_id', 'manifest_id'], ['evidence_manifests.tenant_id', 'evidence_manifests.resident_id', 'evidence_manifests.job_id', 'evidence_manifests.id'], name=op.f('handover_draft_versions_tenant_id_resident_id_job_id_manif_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('handover_draft_versions_pkey')),
    sa.UniqueConstraint('tenant_id', 'job_id', 'id', name=op.f('handover_draft_versions_tenant_id_job_id_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('tenant_id', 'job_id', 'version_number', name=op.f('handover_draft_versions_tenant_id_job_id_version_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('uq_handover_original'), 'handover_draft_versions', ['tenant_id', 'job_id'], unique=True, postgresql_where="(version_kind = 'ai_original'::text)")
    op.drop_index('ix_idempotency_tenant_job', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
