"""add idempotency records

Revision ID: 29e14aedac33
Revises: 0001_handover
"""
from alembic import op
import sqlalchemy as sa

revision = '29e14aedac33'
down_revision = '0001_handover'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(idempotency_key) > 0', name=op.f('ck_idempotency_records_nonempty_idempotency_key')),
    sa.CheckConstraint('length(request_fingerprint) = 64', name=op.f('ck_idempotency_records_sha256_fingerprint_length')),
    sa.ForeignKeyConstraint(['tenant_id', 'job_id'], ['handover_jobs.tenant_id', 'handover_jobs.id'], name='fk_idempotency_tenant_job', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tenant_id', 'actor_id', 'idempotency_key', name=op.f('pk_idempotency_records'))
    )
    op.create_index('ix_idempotency_tenant_job', 'idempotency_records', ['tenant_id', 'job_id'], unique=False)
    op.execute("""
        ALTER TABLE idempotency_records ENABLE ROW LEVEL SECURITY;
        ALTER TABLE idempotency_records FORCE ROW LEVEL SECURITY;

        CREATE POLICY tenant_scope ON idempotency_records
            USING (
                tenant_id = NULLIF(
                    current_setting('intelligence.tenant_id', true),
                    ''
                )::uuid
            )
            WITH CHECK (
                tenant_id = NULLIF(
                    current_setting('intelligence.tenant_id', true),
                    ''
                )::uuid
            );

        REVOKE ALL ON idempotency_records FROM PUBLIC;
        REVOKE ALL ON idempotency_records FROM intelligence_app;

        GRANT SELECT, INSERT
            ON idempotency_records
            TO intelligence_app;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_idempotency_tenant_job', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
